#  ::::::::   ::::::::  ::::    :::  :::::::: ::::::::::: :::     :::::::::  :::        ::::::::::
# :+:    :+: :+:    :+: :+:+:   :+: :+:    :+:    :+:   :+: :+:   :+:    :+: :+:        :+:
# +:+        +:+    +:+ :+:+:+  +:+ +:+           +:+  +:+   +:+  +:+    +:+ +:+        +:+
# +#+        +#+    +:+ +#+ +:+ +#+ +#++:++#++    +#+ +#++:++#++: +#++:++#+  +#+        +#++:++#
# +#+        +#+    +#+ +#+  +#+#+#        +#+    +#+ +#+     +#+ +#+    +#+ +#+        +#+
# #+#    #+# #+#    #+# #+#   #+#+# #+#    #+#    #+# #+#     #+# #+#    #+# #+#        #+#
#  ########   ########  ###    ####  ########     ### ###     ### #########  ########## ##########

merging:
  enable: true
  threshold: 125ms # Format: (N)h (N)m (N)s (N)ms

shuffling:
  enable: true
